"use client"

import Sidebar from "@/components/admin/sidebar"
import { motion } from "framer-motion"
import { Wand2, Layout, FileText, Search, Settings, ArrowRight, Zap, CheckCircle } from "lucide-react"
import { useState } from "react"
import { API_URL } from "@/lib/api"

export default function AdminAIAutomator() {
    const [topic, setTopic] = useState("")
    const [mode, setMode] = useState("seo") // 'standard' or 'seo'
    const [isGenerating, setIsGenerating] = useState(false)
    const [result, setResult] = useState<any>(null)

    const handleAutomate = async () => {
        if (!topic || isGenerating) return
        setIsGenerating(true)

        try {
            // API call to the unified assistant endpoint with an admin-specific system prompt
            let promptMessage = `Generate a blog post about: ${topic}. Include structured headings, a summary, and metadata.`;
            let systemPrompt = "You are an AI Content Strategist. Format your response specifically as a blog post structure.";

            if (mode === 'seo') {
                promptMessage = `Generate an advanced SEO-optimized blog post about: ${topic}. Follow these strict rules:
1. Include a highly engaging, click-worthy SEO Title and meta description at the very top.
2. Structure the content with clear H1, H2, and H3 headings optimized for search intent.
3. Strategically place LSI (Latent Semantic Indexing) keywords naturally throughout the text.
4. Include a 'Key Takeaways' bulleted list right after the introduction.
5. Provide actionable advice or data points to increase time-on-page and reader value.
6. The content must be comprehensive, at least 1000 words if possible.`;
                systemPrompt = "You are an elite SEO Expert and AI Content Strategist. Your goal is to write blog posts that rank #1 on Google. Format your response specifically as a blog post structure with clear metadata.";
            }

            const response = await fetch(`${API_URL}/ai/assistant`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    message: promptMessage,
                    system_prompt: systemPrompt
                })
            })
            const data = await response.json()
            setResult({
                title: `Auto-generated: ${topic}`,
                content: data.response,
                meta: {
                    title: `SEO Title for ${topic}`,
                    description: `A comprehensive look into ${topic} generated by AI Era Automator.`
                }
            })
        } catch (err) {
            console.error(err)
        } finally {
            setIsGenerating(false)
        }
    }

    return (
        <div className="flex min-h-screen bg-background">
            <Sidebar />
            <main className="flex-1 p-8 overflow-y-auto">
                <header className="mb-12">
                    <h1 className="text-3xl font-bold flex items-center gap-3">
                        <Wand2 className="text-primary w-8 h-8" />
                        Admin <span className="text-primary font-black">AI Automator</span>
                    </h1>
                    <p className="text-muted-foreground">Automate content creation and platform management tasks using AI.</p>
                </header>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Control Panel */}
                    <div className="space-y-6">
                        <div className="glass-card p-8">
                            <h3 className="text-lg font-bold mb-6 flex items-center gap-2">
                                <Zap className="w-5 h-5 text-primary" />
                                Quick Content Generation
                            </h3>

                            <div className="space-y-4">
                                <div className="space-y-2">
                                    <label className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Blog Topic</label>
                                    <input
                                        type="text"
                                        value={topic}
                                        onChange={(e) => setTopic(e.target.value)}
                                        placeholder="e.g., The Future of Multi-Agent Systems"
                                        className="w-full bg-secondary/50 border border-border rounded-xl px-4 py-3 text-sm focus:ring-primary/50"
                                    />
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div
                                        onClick={() => setMode('standard')}
                                        className={`p-4 rounded-xl border cursor-pointer transition-all ${mode === 'standard' ? 'border-primary bg-primary/10 shadow-[0_0_15px_rgba(var(--primary),0.2)]' : 'border-border bg-secondary/20 hover:border-primary/30'}`}
                                    >
                                        <FileText className={`w-5 h-5 mb-2 ${mode === 'standard' ? 'text-primary' : 'text-muted-foreground'}`} />
                                        <p className="text-xs font-bold transition-colors">Standard Blog</p>
                                    </div>
                                    <div
                                        onClick={() => setMode('seo')}
                                        className={`p-4 rounded-xl border cursor-pointer transition-all relative overflow-hidden ${mode === 'seo' ? 'border-primary bg-primary/10 shadow-[0_0_15px_rgba(var(--primary),0.2)]' : 'border-border bg-secondary/20 hover:border-primary/30'}`}
                                    >
                                        <Zap className={`w-5 h-5 mb-2 ${mode === 'seo' ? 'text-primary' : 'text-muted-foreground'}`} />
                                        <p className="text-xs font-bold transition-colors">SEO Optimized</p>
                                        <div className="absolute top-0 right-0 p-1 bg-primary text-[8px] text-white font-black uppercase shadow-sm">Pro</div>
                                    </div>
                                </div>

                                <button
                                    onClick={handleAutomate}
                                    disabled={isGenerating || !topic}
                                    className="w-full py-4 ai-gradient rounded-xl font-bold text-white ai-glow flex items-center justify-center gap-2 group disabled:opacity-50"
                                >
                                    {isGenerating ? "AI Processing..." : "Automate Content"}
                                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                                </button>
                            </div>
                        </div>

                        <div className="glass-card p-6 border-blue-500/20">
                            <h4 className="font-bold text-sm mb-4">Automation Logs</h4>
                            <div className="space-y-3 font-mono text-[10px]">
                                <div className="flex items-center gap-2 text-green-500">
                                    <span className="w-1.5 h-1.5 rounded-full bg-green-500" />
                                    [10:35:12] OpenRouter Session Initialized.
                                </div>
                                <div className="flex items-center gap-2 text-muted-foreground">
                                    <span className="w-1.5 h-1.5 rounded-full bg-secondary" />
                                    [10:35:14] Waiting for user input...
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Preview Panel */}
                    <div className="min-h-[500px]">
                        {result ? (
                            <motion.div
                                initial={{ opacity: 0, scale: 0.95 }}
                                animate={{ opacity: 1, scale: 1 }}
                                className="glass-card p-8 h-full bg-black/40 border-primary/20 relative flex flex-col"
                            >
                                <div className="flex justify-between items-start mb-6">
                                    <h2 className="text-2xl font-bold text-primary flex-1 pr-4">{result.title}</h2>
                                    <button
                                        onClick={async () => {
                                            try {
                                                const btn = document.getElementById('automator-publish-btn');
                                                if (btn) btn.innerHTML = '<span class="flex items-center gap-2">Publishing... <svg class="animate-spin w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg></span>';

                                                const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
                                                const response = await fetch(`${API_URL}/blogs/`, {
                                                    method: "POST",
                                                    headers: { "Content-Type": "application/json" },
                                                    body: JSON.stringify({
                                                        title: result.title,
                                                        slug: slug,
                                                        content: result.content,
                                                        category: "AI Generated",
                                                        tags: ["Auto"],
                                                        seo_title: result.meta?.title || result.title,
                                                        seo_description: result.meta?.description || ""
                                                    })
                                                });

                                                if (response.ok) {
                                                    if (btn) {
                                                        btn.className = "px-6 py-2 rounded-lg bg-green-500 text-white font-bold flex items-center gap-2 shadow-[0_0_15px_rgba(34,197,94,0.5)]";
                                                        btn.innerHTML = '<span class="flex items-center gap-2"><svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"></path></svg> Published!</span>';
                                                    }
                                                } else {
                                                    alert("Failed to publish blog.");
                                                    if (btn) btn.innerHTML = "Publish to Blog";
                                                }
                                            } catch (e) {
                                                console.error(e);
                                                alert("Error publishing blog.");
                                                const btn = document.getElementById('automator-publish-btn');
                                                if (btn) btn.innerHTML = "Publish to Blog";
                                            }
                                        }}
                                        id="automator-publish-btn"
                                        className="px-6 py-2 rounded-lg text-white font-bold text-sm flex items-center gap-2 transition-all ai-gradient ai-glow hover:scale-105 active:scale-95 whitespace-nowrap"
                                    >
                                        <CheckCircle className="w-4 h-4" /> Publish to Blog
                                    </button>
                                </div>

                                <div className="prose prose-invert prose-sm max-w-none mb-8 text-muted-foreground overflow-y-auto flex-1 pr-2 custom-scrollbar">
                                    {result.content}
                                </div>

                                <div className="space-y-4 pt-6 border-t border-border mt-auto">
                                    <div className="bg-secondary/30 p-4 rounded-xl">
                                        <p className="text-[10px] font-bold uppercase text-primary mb-2">AI Suggested Meta Title</p>
                                        <p className="text-xs font-mono">{result.meta.title}</p>
                                    </div>
                                    <div className="bg-secondary/30 p-4 rounded-xl">
                                        <p className="text-[10px] font-bold uppercase text-primary mb-2">AI Suggested Meta Description</p>
                                        <p className="text-xs font-mono">{result.meta.description}</p>
                                    </div>
                                </div>
                            </motion.div>
                        ) : (
                            <div className="glass-card h-full flex flex-col items-center justify-center text-center opacity-40 border-dashed border-2">
                                <Wand2 className="w-12 h-12 mb-4 text-muted-foreground" />
                                <h4 className="font-bold text-muted-foreground">Generation Preview</h4>
                                <p className="text-xs text-muted-foreground max-w-[200px] mt-2">Enter a topic and click automate to see AI magic here.</p>
                            </div>
                        )}
                    </div>
                </div>
            </main>
        </div>
    )
}
